"use client";

import React,{useEffect,useMemo,useState}from"react";
import{CalendarDays,Wallet,Plus,Download,Upload,BellRing,Home,Target,Settings,Trash2,CheckCircle2,Undo2,Sparkles,Search,RefreshCw,CreditCard,PiggyBank,ShoppingBag,TrendingDown,Printer,PartyPopper}from"lucide-react";

type Bill={id:string;name:string;amount:number;dueDate:string;category:string;frequency:"once"|"weekly"|"fortnightly"|"monthly"|"quarterly"|"yearly";paid:boolean;autopay:boolean;priority:"low"|"normal"|"high";notes:string};
type Income={id:string;source:string;amount:number;date:string;frequency:"once"|"weekly"|"fortnightly"|"monthly"};
type Goal={id:string;name:string;target:number;saved:number;dueDate:string;color:string};
type Debt={id:string;name:string;balance:number;minimum:number;rate:number;dueDate:string};
type Pot={id:string;name:string;balance:number;target:number;emoji:string};
type Wish={id:string;name:string;cost:number;priority:string;notes:string};
type SettingsType={currency:string;payday:string;safetyBuffer:number;homeAssistantWebhook:string;themeName:string};

const CATS=["Home","Utilities","Phone / Internet","Car","Food","Insurance","Subscriptions","Kids","Health","Debt","Business","Fun","Other"];
const todayISO=()=>new Date().toISOString().slice(0,10);
const todayPlus=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const money=(n:number,c="AUD")=>new Intl.NumberFormat("en-AU",{style:"currency",currency:c}).format(Number.isFinite(n)?n:0);
const daysUntil=(date:string)=>Math.round((new Date(date).getTime()-new Date(todayISO()).getTime())/86400000);
const monthlyBill=(amount:number,f:Bill["frequency"])=>f==="weekly"?amount*52/12:f==="fortnightly"?amount*26/12:f==="quarterly"?amount/3:f==="yearly"?amount/12:amount;
const monthlyIncome=(amount:number,f:Income["frequency"])=>f==="weekly"?amount*52/12:f==="fortnightly"?amount*26/12:amount;
function addFrequency(date:string,f:Bill["frequency"]|Income["frequency"]){const d=new Date(date);if(f==="weekly")d.setDate(d.getDate()+7);if(f==="fortnightly")d.setDate(d.getDate()+14);if(f==="monthly")d.setMonth(d.getMonth()+1);if(f==="quarterly")d.setMonth(d.getMonth()+3);if(f==="yearly")d.setFullYear(d.getFullYear()+1);return d.toISOString().slice(0,10)}
function useLS<T>(key:string,fallback:T){const[v,setV]=useState<T>(fallback);useEffect(()=>{try{const s=localStorage.getItem(key);if(s)setV(JSON.parse(s))}catch{}},[key]);useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(v))}catch{}},[key,v]);return[v,setV]as const}

const starterBills:Bill[]=[
{id:crypto.randomUUID(),name:"Rent / Mortgage",amount:450,dueDate:todayPlus(3),category:"Home",frequency:"weekly",paid:false,autopay:false,priority:"high",notes:"Main housing payment"},
{id:crypto.randomUUID(),name:"Electricity",amount:180,dueDate:todayPlus(9),category:"Utilities",frequency:"quarterly",paid:false,autopay:false,priority:"normal",notes:""},
{id:crypto.randomUUID(),name:"Phone",amount:65,dueDate:todayPlus(12),category:"Phone / Internet",frequency:"monthly",paid:false,autopay:true,priority:"normal",notes:""},
{id:crypto.randomUUID(),name:"Streaming bundle",amount:29,dueDate:todayPlus(5),category:"Subscriptions",frequency:"monthly",paid:false,autopay:true,priority:"low",notes:"Check if still needed"}
];

export default function App(){
const[bills,setBills]=useLS<Bill[]>("mm2_bills",starterBills);
const[incomes,setIncomes]=useLS<Income[]>("mm2_incomes",[{id:crypto.randomUUID(),source:"Pay",amount:1250,date:todayPlus(5),frequency:"weekly"}]);
const[goals,setGoals]=useLS<Goal[]>("mm2_goals",[{id:crypto.randomUUID(),name:"Emergency buffer",target:2000,saved:350,dueDate:todayPlus(90),color:"green"},{id:crypto.randomUUID(),name:"Holiday / fun",target:900,saved:120,dueDate:todayPlus(160),color:"purple"}]);
const[debts,setDebts]=useLS<Debt[]>("mm2_debts",[{id:crypto.randomUUID(),name:"Credit card",balance:1200,minimum:75,rate:18.9,dueDate:todayPlus(16)}]);
const[pots,setPots]=useLS<Pot[]>("mm2_pots",[{id:crypto.randomUUID(),name:"Fuel",balance:80,target:140,emoji:"⛽"},{id:crypto.randomUUID(),name:"Groceries",balance:210,target:300,emoji:"🛒"},{id:crypto.randomUUID(),name:"Kids",balance:60,target:150,emoji:"🧸"}]);
const[wishes,setWishes]=useLS<Wish[]>("mm2_wishes",[{id:crypto.randomUUID(),name:"New tablet dashboard",cost:250,priority:"medium",notes:"For Home Assistant / budget display"}]);
const[settings,setSettings]=useLS<SettingsType>("mm2_settings",{currency:"AUD",payday:todayPlus(5),safetyBuffer:300,homeAssistantWebhook:"",themeName:"Colour Pop"});
const[tab,setTab]=useState("dashboard");const[modal,setModal]=useState<any>(null);const[search,setSearch]=useState("");const[monthOffset,setMonthOffset]=useState(0);

const upcoming=useMemo(()=>bills.filter(b=>!b.paid).sort((a,b)=>new Date(a.dueDate).getTime()-new Date(b.dueDate).getTime()),[bills]);
const paid=bills.filter(b=>b.paid),dueSoon=upcoming.filter(b=>daysUntil(b.dueDate)<=14),overdue=upcoming.filter(b=>daysUntil(b.dueDate)<0);
const mBills=bills.reduce((s,b)=>s+monthlyBill(b.amount,b.frequency),0)+debts.reduce((s,d)=>s+d.minimum,0);
const mIncome=incomes.reduce((s,i)=>s+monthlyIncome(i.amount,i.frequency),0);
const left=mIncome-mBills;const saved=goals.reduce((s,g)=>s+g.saved,0)+pots.reduce((s,p)=>s+p.balance,0);const debtTotal=debts.reduce((s,d)=>s+d.balance,0);
const categoryTotals=CATS.map(c=>({cat:c,total:bills.filter(b=>b.category===c).reduce((s,b)=>s+monthlyBill(b.amount,b.frequency),0)})).filter(x=>x.total>0).sort((a,b)=>b.total-a.total);
const nextBill=upcoming[0];

async function ha(message:string){if(!settings.homeAssistantWebhook)return alert("Add your Home Assistant webhook in Settings first.");try{await fetch(settings.homeAssistantWebhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,dueSoon:dueSoon.length,overdue:overdue.length,leftover:left,nextBill:nextBill?.name})});alert("Sent to Home Assistant.")}catch{alert("Home Assistant webhook failed. Check the URL.")}}
function markPaid(id:string){setBills(p=>p.map(b=>b.id!==id?b:(b.frequency==="once"?{...b,paid:true}:{...b,dueDate:addFrequency(b.dueDate,b.frequency),paid:false})))}
function exportData(){const blob=new Blob([JSON.stringify({bills,incomes,goals,debts,pots,wishes,settings},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`moneymate-backup-${todayISO()}.json`;a.click()}
function exportICS(){const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//MoneyMate//Bills//EN"];upcoming.forEach(b=>{lines.push("BEGIN:VEVENT",`UID:${b.id}@moneymate`,`DTSTAMP:${todayISO().replaceAll("-","")}T000000Z`,`DTSTART;VALUE=DATE:${b.dueDate.replaceAll("-","")}`,`SUMMARY:${b.name} due - ${money(b.amount,settings.currency)}`,`DESCRIPTION:${b.category} ${b.notes||""}`,"END:VEVENT")});lines.push("END:VCALENDAR");const blob=new Blob([lines.join("\r\n")],{type:"text/calendar"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`moneymate-bills-${todayISO()}.ics`;a.click()}
function importData(file:File){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(d.bills)setBills(d.bills);if(d.incomes)setIncomes(d.incomes);if(d.goals)setGoals(d.goals);if(d.debts)setDebts(d.debts);if(d.pots)setPots(d.pots);if(d.wishes)setWishes(d.wishes);if(d.settings)setSettings(d.settings)}catch{alert("Backup import failed")}};r.readAsText(file)}
const filtered=bills.filter(b=>`${b.name} ${b.category} ${b.notes}`.toLowerCase().includes(search.toLowerCase()));

return <main className="appShell"><div className="container">
 <div className="topbar"><div className="brand"><div className="logo"><Wallet/></div><span>MoneyMate Colour</span></div><div className="quickActions"><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/> Print</button><button className="btn secondary" onClick={()=>setModal("settings")}><Settings size={16}/> Settings</button></div></div>
 <section className="hero"><div className="heroCard"><div className="pillRow"><span className="pill green"><Sparkles size={13}/> Bright Vercel budget app</span><span className="pill orange">Bills + calendar</span><span className="pill pink">Savings + debts</span></div><h1>Know where your money is going.</h1><p>A colourful live dashboard for bills, income, subscriptions, debts, savings pots, wish list items, alerts, calendar dates, backups and Home Assistant linking.</p><div className="quickActions"><button className="btn" onClick={()=>setModal("bill")}><Plus size={16}/> Add bill</button><button className="btn green" onClick={()=>setModal("income")}><Wallet size={16}/> Add income</button><button className="btn orange" onClick={()=>setModal("goal")}><Target size={16}/> Add goal</button><button className="btn secondary" onClick={()=>ha("MoneyMate budget check requested.")}><Home size={16}/> HA check</button></div></div>
 <div className="panel"><div className="sectionTitle"><h2>Money pulse</h2><PartyPopper/></div><div className="moneyBig">{money(left,settings.currency)}</div><div className="muted">estimated monthly leftover after bills and debt minimums</div><div className="list" style={{marginTop:14}}><div className="item"><div className="itemTop"><b>Next bill</b><span className="pill orange">{nextBill?nextBill.dueDate:"None"}</span></div><span>{nextBill?`${nextBill.name} — ${money(nextBill.amount,settings.currency)}`:"No upcoming bills"}</span></div><div className="item"><div className="itemTop"><b>Safety buffer</b><span>{money(settings.safetyBuffer,settings.currency)}</span></div><div className="progress"><div style={{width:`${Math.min(100,Math.max(0,left/settings.safetyBuffer*100))}%`}}/></div></div></div></div></section>
 <section className="grid stats"><Stat label="Income / month" value={money(mIncome,settings.currency)}/><Stat label="Bills / month" value={money(mBills,settings.currency)}/><Stat label="Due soon" value={`${dueSoon.length}`}/><Stat label="Saved + pots" value={money(saved,settings.currency)}/><Stat label="Debt balance" value={money(debtTotal,settings.currency)}/></section>
 <nav className="tabs">{[["dashboard","Dashboard",Sparkles],["bills","Bills",CalendarDays],["calendar","Calendar",CalendarDays],["pots","Money pots",PiggyBank],["goals","Goals",Target],["debts","Debts",CreditCard],["wishlist","Wish list",ShoppingBag],["tools","Tools",Settings]].map(([id,name,Icon]:any)=><button key={id} className={`tab ${tab===id?"active":""}`} onClick={()=>setTab(id)}><Icon size={16}/>{name}</button>)}</nav>
 {tab==="dashboard"&&<section className="mainGrid"><Panel title="Upcoming bills"><BillList bills={upcoming.slice(0,9)} settings={settings} onPaid={markPaid} onDelete={id=>setBills(p=>p.filter(b=>b.id!==id))}/></Panel><Panel title="Smart summary"><div className="list">{overdue.length>0&&<Alert text={`${overdue.length} overdue bill${overdue.length>1?"s":""}.`}/>}<div className="item"><b>Weekly amount to set aside</b><span className="moneyBig" style={{fontSize:30}}>{money(mBills/4.33,settings.currency)}</span><span className="muted">Smooths out your regular bills.</span></div><MiniBars data={categoryTotals} currency={settings.currency}/></div></Panel></section>}
 {tab==="bills"&&<Panel title="All bills and subscriptions"><div className="field" style={{marginBottom:12}}><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search bill, category, note..."/></div><BillList bills={filtered} settings={settings} onPaid={markPaid} onUndo={id=>setBills(p=>p.map(b=>b.id===id?{...b,paid:false}:b))} onDelete={id=>setBills(p=>p.filter(b=>b.id!==id))}/></Panel>}
 {tab==="calendar"&&<Panel title="Colour bills calendar"><div className="quickActions" style={{marginBottom:12}}><button className="btn secondary" onClick={()=>setMonthOffset(v=>v-1)}>Previous</button><button className="btn secondary" onClick={()=>setMonthOffset(0)}>Today</button><button className="btn secondary" onClick={()=>setMonthOffset(v=>v+1)}>Next</button><button className="btn secondary" onClick={exportICS}>Export calendar</button></div><Calendar bills={upcoming} monthOffset={monthOffset} settings={settings}/></Panel>}
 {tab==="pots"&&<Panel title="Money pots"><div className="threeGrid">{pots.map(p=><div className="miniCard panel" key={p.id}><div className="emoji">{p.emoji}</div><h2>{p.name}</h2><div className="moneyBig" style={{fontSize:30}}>{money(p.balance,settings.currency)}</div><div className="progress"><div style={{width:`${Math.min(100,p.balance/p.target*100)}%`}}/></div><p className="muted">Target {money(p.target,settings.currency)}</p><div className="smallBtns"><button className="iconBtn" onClick={()=>{const n=Number(prompt("Add amount","20")||0);if(n)setPots(x=>x.map(y=>y.id===p.id?{...y,balance:y.balance+n}:y))}}>Add</button><button className="iconBtn" onClick={()=>setPots(x=>x.filter(y=>y.id!==p.id))}>Delete</button></div></div>)}<button className="miniCard panel" onClick={()=>setModal("pot")}><Plus/> Add money pot</button></div></Panel>}
 {tab==="goals"&&<Panel title="Savings goals"><div className="threeGrid">{goals.map(g=><div className="miniCard panel" key={g.id}><Target/><h2>{g.name}</h2><div className="progress"><div style={{width:`${Math.min(100,g.saved/g.target*100)}%`}}/></div><p><b>{money(g.saved,settings.currency)}</b> of {money(g.target,settings.currency)}</p><p className="muted">Due {g.dueDate}</p><div className="smallBtns"><button className="iconBtn" onClick={()=>{const n=Number(prompt("Add saved amount","50")||0);if(n)setGoals(x=>x.map(y=>y.id===g.id?{...y,saved:y.saved+n}:y))}}>Add money</button><button className="iconBtn" onClick={()=>setGoals(x=>x.filter(y=>y.id!==g.id))}>Delete</button></div></div>)}</div></Panel>}
 {tab==="debts"&&<Panel title="Debt tracker"><div className="quickActions" style={{marginBottom:12}}><button className="btn" onClick={()=>setModal("debt")}><Plus size={16}/> Add debt</button></div><div className="list">{debts.map(d=><div className="item" key={d.id}><div className="itemTop"><div><div className="itemName">{d.name}</div><span className="muted">APR {d.rate}% · minimum {money(d.minimum,settings.currency)}</span></div><b>{money(d.balance,settings.currency)}</b></div><span className="pill red">Due {d.dueDate}</span><div className="smallBtns"><button className="iconBtn" onClick={()=>{const n=Number(prompt("Payment amount","50")||0);if(n)setDebts(x=>x.map(y=>y.id===d.id?{...y,balance:Math.max(0,y.balance-n)}:y))}}>Log payment</button><button className="iconBtn" onClick={()=>setDebts(x=>x.filter(y=>y.id!==d.id))}>Delete</button></div></div>)}</div></Panel>}
 {tab==="wishlist"&&<Panel title="Wish list / planned buys"><div className="quickActions" style={{marginBottom:12}}><button className="btn" onClick={()=>setModal("wish")}><Plus size={16}/> Add wish</button></div><div className="list">{wishes.map(w=><div className="item" key={w.id}><div className="itemTop"><div><div className="itemName">{w.name}</div><span className="muted">{w.notes}</span></div><b>{money(w.cost,settings.currency)}</b></div><span className="pill pink">Priority {w.priority}</span><button className="iconBtn" onClick={()=>setWishes(x=>x.filter(y=>y.id!==w.id))}>Delete</button></div>)}</div></Panel>}
 {tab==="tools"&&<Panel title="Tools, backup and Home Assistant"><div className="threeGrid"><Tool title="Backup" text="Download your whole budget as JSON." icon={<Download/>} action={exportData}/><Tool title="Restore" text="Import a JSON backup." icon={<Upload/>} fileAction={importData}/><Tool title="Calendar export" text="Export bills as .ics." icon={<CalendarDays/>} action={exportICS}/><Tool title="Home Assistant" text="Open webhook and iframe setup." icon={<Home/>} action={()=>setModal("settings")}/><Tool title="Print report" text="Print or save as PDF." icon={<Printer/>} action={()=>window.print()}/><Tool title="Reset demo data" text="Clear browser data manually from dev tools if needed." icon={<RefreshCw/>}/></div></Panel>}
 {modal&&<EditModal modal={modal} close={()=>setModal(null)} settings={settings} setSettings={setSettings} setBills={setBills} setIncomes={setIncomes} setGoals={setGoals} setDebts={setDebts} setPots={setPots} setWishes={setWishes}/>}
 </div></main>
}

function Stat({label,value}:{label:string;value:string}){return <div className="statCard"><div className="label">{label}</div><div className="value">{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="sectionTitle"><h2>{title}</h2></div>{children}</section>}
function Alert({text}:{text:string}){return <div className="item" style={{borderColor:"#fecaca",background:"#fff1f2"}}><b>Heads up</b><span className="muted">{text}</span></div>}
function MiniBars({data,currency}:{data:{cat:string,total:number}[],currency:string}){const max=Math.max(...data.map(d=>d.total),1);return <div className="item"><b>Bill categories</b><div className="barList">{data.slice(0,7).map(d=><div className="barRow" key={d.cat}><span>{d.cat}</span><div className="bar"><div style={{width:`${d.total/max*100}%`}}/></div><span>{money(d.total,currency)}</span></div>)}</div></div>}
function BillList({bills,settings,onPaid,onDelete,onUndo}:{bills:Bill[];settings:SettingsType;onPaid:(id:string)=>void;onDelete:(id:string)=>void;onUndo?:(id:string)=>void}){if(!bills.length)return <div className="item"><b>Nothing here yet.</b><span className="muted">Add something to start tracking.</span></div>;return <div className="list">{bills.map(b=>{const d=daysUntil(b.dueDate);return <div className="item" key={b.id}><div className="itemTop"><div><div className="itemName">{b.name}</div><span className="muted">{b.category} · {b.frequency}{b.autopay?" · autopay":""}</span></div><b>{money(b.amount,settings.currency)}</b></div><div className="pillRow"><span className={`pill ${b.paid?"green":d<8?"red":"orange"}`}>{b.paid?"Paid":d<0?`${Math.abs(d)} days overdue`:`Due in ${d} days`}</span><span className="pill">{b.dueDate}</span><span className={`pill ${b.priority==="high"?"red":b.priority==="low"?"green":"orange"}`}>{b.priority}</span></div>{b.notes&&<span className="muted">{b.notes}</span>}<div className="smallBtns">{!b.paid&&<button className="iconBtn" onClick={()=>onPaid(b.id)}><CheckCircle2 size={14}/> Paid / roll forward</button>}{b.paid&&onUndo&&<button className="iconBtn" onClick={()=>onUndo(b.id)}><Undo2 size={14}/> Undo</button>}<button className="iconBtn" onClick={()=>onDelete(b.id)}><Trash2 size={14}/> Delete</button></div></div>})}</div>}
function Calendar({bills,monthOffset,settings}:{bills:Bill[];monthOffset:number;settings:SettingsType}){const base=new Date();base.setMonth(base.getMonth()+monthOffset);const y=base.getFullYear(),m=base.getMonth();const start=new Date(y,m,1),end=new Date(y,m+1,0);const blanks=(start.getDay()+6)%7;const days=Array.from({length:blanks+end.getDate()},(_,i)=>i<blanks?null:i-blanks+1);return <><h2>{base.toLocaleString("en-AU",{month:"long",year:"numeric"})}</h2><div className="calendar">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div className="dayHead" key={d}>{d}</div>)}{days.map((day,i)=>{if(!day)return <div key={i}/>;const iso=new Date(y,m,day+1).toISOString().slice(0,10);const bs=bills.filter(b=>b.dueDate===iso);return <div className={`day ${iso===todayISO()?"today":""}`} key={i}><div className="dayNum">{day}</div>{bs.map(b=><div className="calBill" key={b.id}>{b.name} {money(b.amount,settings.currency)}</div>)}</div>})}</div></>}
function Tool({title,text,icon,action,fileAction}:{title:string;text:string;icon:React.ReactNode;action?:()=>void;fileAction?:(f:File)=>void}){return <div className="miniCard panel"><div className="itemTop"><h2>{title}</h2>{icon}</div><p className="muted">{text}</p>{action&&<button className="btn secondary" onClick={action}>Open</button>}{fileAction&&<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&fileAction(e.target.files[0])}/>}</div>}
function Field({label,children,full}:{label:string;children:React.ReactNode;full?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{children}</div>}
function ModalShell({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="modalOverlay"><div className="modalCard"><div className="sectionTitle"><h2>{title}</h2><button className="iconBtn" onClick={close}>Close</button></div>{children}</div></div>}
function EditModal(p:any){const{modal,close,settings,setSettings,setBills,setIncomes,setGoals,setDebts,setPots,setWishes}=p;const[f,setF]=useState<any>({date:todayISO(),dueDate:todayISO(),frequency:"monthly",category:"General",priority:"normal",autopay:false,amount:"",name:"",notes:"",source:"",target:"",saved:"0",balance:"",minimum:"",rate:"0",emoji:"💰",cost:"",payday:settings.payday,currency:settings.currency,safetyBuffer:settings.safetyBuffer,homeAssistantWebhook:settings.homeAssistantWebhook,themeName:settings.themeName});
 if(modal==="settings")return <ModalShell title="Settings + Home Assistant" close={close}><div className="formGrid"><Field label="Currency"><input value={f.currency} onChange={e=>setF({...f,currency:e.target.value.toUpperCase()})}/></Field><Field label="Next payday"><input type="date" value={f.payday} onChange={e=>setF({...f,payday:e.target.value})}/></Field><Field label="Safety buffer"><input type="number" value={f.safetyBuffer} onChange={e=>setF({...f,safetyBuffer:Number(e.target.value)})}/></Field><Field label="Theme name"><input value={f.themeName} onChange={e=>setF({...f,themeName:e.target.value})}/></Field><Field label="Home Assistant webhook URL" full><input value={f.homeAssistantWebhook} onChange={e=>setF({...f,homeAssistantWebhook:e.target.value})} placeholder="https://your-ha/api/webhook/moneymate"/></Field><Field label="HA iframe panel" full><textarea readOnly value={`panel_iframe:\n  moneymate:\n    title: MoneyMate\n    icon: mdi:cash-clock\n    url: https://YOUR-VERCEL-APP.vercel.app`}/></Field></div><br/><button className="btn" onClick={()=>{setSettings({currency:f.currency,payday:f.payday,safetyBuffer:Number(f.safetyBuffer),homeAssistantWebhook:f.homeAssistantWebhook,themeName:f.themeName});close()}}>Save settings</button></ModalShell>;
 return <ModalShell title={`Add ${modal}`} close={close}><div className="formGrid">
 {["bill","goal","debt","pot","wish"].includes(modal)&&<Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field>}
 {modal==="income"&&<Field label="Source"><input value={f.source} onChange={e=>setF({...f,source:e.target.value})}/></Field>}
 {["bill","income"].includes(modal)&&<Field label="Amount"><input type="number" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field>}
 {modal==="bill"&&<><Field label="Due date"><input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></Field><Field label="Category"><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Frequency"><select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{["once","weekly","fortnightly","monthly","quarterly","yearly"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}>{["low","normal","high"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Autopay"><select value={String(f.autopay)} onChange={e=>setF({...f,autopay:e.target.value==="true"})}><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Notes" full><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></>}
 {modal==="income"&&<><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Frequency"><select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{["once","weekly","fortnightly","monthly"].map(x=><option key={x}>{x}</option>)}</select></Field></>}
 {modal==="goal"&&<><Field label="Target"><input type="number" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></Field><Field label="Already saved"><input type="number" value={f.saved} onChange={e=>setF({...f,saved:e.target.value})}/></Field><Field label="Due date"><input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></Field></>}
 {modal==="debt"&&<><Field label="Balance"><input type="number" value={f.balance} onChange={e=>setF({...f,balance:e.target.value})}/></Field><Field label="Minimum payment"><input type="number" value={f.minimum} onChange={e=>setF({...f,minimum:e.target.value})}/></Field><Field label="Interest rate %"><input type="number" value={f.rate} onChange={e=>setF({...f,rate:e.target.value})}/></Field><Field label="Due date"><input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></Field></>}
 {modal==="pot"&&<><Field label="Emoji"><input value={f.emoji} onChange={e=>setF({...f,emoji:e.target.value})}/></Field><Field label="Balance"><input type="number" value={f.balance} onChange={e=>setF({...f,balance:e.target.value})}/></Field><Field label="Target"><input type="number" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></Field></>}
 {modal==="wish"&&<><Field label="Cost"><input type="number" value={f.cost} onChange={e=>setF({...f,cost:e.target.value})}/></Field><Field label="Priority"><input value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}/></Field><Field label="Notes" full><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></>}
 </div><br/><button className="btn" onClick={()=>{if(modal==="bill")setBills((x:Bill[])=>[{id:crypto.randomUUID(),name:f.name,amount:Number(f.amount),dueDate:f.dueDate,category:f.category,frequency:f.frequency,paid:false,autopay:f.autopay,priority:f.priority,notes:f.notes},...x]);if(modal==="income")setIncomes((x:Income[])=>[{id:crypto.randomUUID(),source:f.source,amount:Number(f.amount),date:f.date,frequency:f.frequency},...x]);if(modal==="goal")setGoals((x:Goal[])=>[{id:crypto.randomUUID(),name:f.name,target:Number(f.target),saved:Number(f.saved),dueDate:f.dueDate,color:"green"},...x]);if(modal==="debt")setDebts((x:Debt[])=>[{id:crypto.randomUUID(),name:f.name,balance:Number(f.balance),minimum:Number(f.minimum),rate:Number(f.rate),dueDate:f.dueDate},...x]);if(modal==="pot")setPots((x:Pot[])=>[{id:crypto.randomUUID(),name:f.name,balance:Number(f.balance),target:Number(f.target),emoji:f.emoji},...x]);if(modal==="wish")setWishes((x:Wish[])=>[{id:crypto.randomUUID(),name:f.name,cost:Number(f.cost),priority:f.priority,notes:f.notes},...x]);close()}}>Save</button></ModalShell>}
