"use client";

import React,{useEffect,useMemo,useState}from"react";
import{BarChart3,CalendarDays,Wallet,Plus,Download,Settings,Trash2,CheckCircle2,Sparkles,Printer,Calculator,ReceiptText,Edit3,Save,X,FileSpreadsheet}from"lucide-react";

type Bill={id:string;name:string;amount:number;dueDate:string;category:string;frequency:"once"|"weekly"|"fortnightly"|"monthly"|"quarterly"|"yearly";paid:boolean;autopay:boolean;notes:string};
type Income={id:string;source:string;amount:number;date:string;frequency:"once"|"weekly"|"fortnightly"|"monthly";taxable:boolean;notes:string};
type Expense={id:string;name:string;amount:number;date:string;category:string;taxDeductible:boolean;gstIncluded:boolean;notes:string};
type SettingsType={currency:string;payday:string;safetyBuffer:number;homeAssistantWebhook:string;taxRate:number};

const CATS=["Home","Utilities","Phone / Internet","Car","Food","Insurance","Subscriptions","Kids","Health","Debt","Business","Tools","Fuel","Fun","Other"];
const EXPENSE_CATS=["Tools","Fuel","Materials","Phone","Internet","Vehicle","Insurance","Marketing","Office","Training","Repairs","Bank Fees","Other"];
const todayISO=()=>new Date().toISOString().slice(0,10);
const todayPlus=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const money=(n:number,c="AUD")=>new Intl.NumberFormat("en-AU",{style:"currency",currency:c}).format(Number.isFinite(n)?n:0);
const daysUntil=(date:string)=>Math.round((new Date(date).getTime()-new Date(todayISO()).getTime())/86400000);
const monthlyBill=(a:number,f:Bill["frequency"])=>f==="weekly"?a*52/12:f==="fortnightly"?a*26/12:f==="quarterly"?a/3:f==="yearly"?a/12:a;
const monthlyIncome=(a:number,f:Income["frequency"])=>f==="weekly"?a*52/12:f==="fortnightly"?a*26/12:f==="monthly"?a:a;
function addFreq(date:string,f:Bill["frequency"]){const d=new Date(date);if(f==="weekly")d.setDate(d.getDate()+7);if(f==="fortnightly")d.setDate(d.getDate()+14);if(f==="monthly")d.setMonth(d.getMonth()+1);if(f==="quarterly")d.setMonth(d.getMonth()+3);if(f==="yearly")d.setFullYear(d.getFullYear()+1);return d.toISOString().slice(0,10)}
function monthKey(d:string){return d.slice(0,7)}
function useLS<T>(k:string,f:T){const[v,setV]=useState<T>(f);useEffect(()=>{try{const s=localStorage.getItem(k);if(s)setV(JSON.parse(s))}catch{}},[k]);useEffect(()=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},[k,v]);return[v,setV]as const}

export default function App(){
const[bills,setBills]=useLS<Bill[]>("mmb_bills",[
{id:crypto.randomUUID(),name:"Rent / Mortgage",amount:450,dueDate:todayPlus(3),category:"Home",frequency:"weekly",paid:false,autopay:false,notes:"Main housing payment"},
{id:crypto.randomUUID(),name:"Electricity",amount:180,dueDate:todayPlus(9),category:"Utilities",frequency:"quarterly",paid:false,autopay:false,notes:""},
{id:crypto.randomUUID(),name:"Phone",amount:65,dueDate:todayPlus(12),category:"Phone / Internet",frequency:"monthly",paid:false,autopay:true,notes:""}
]);
const[incomes,setIncomes]=useLS<Income[]>("mmb_incomes",[
{id:crypto.randomUUID(),source:"Main pay",amount:1250,date:todayPlus(5),frequency:"weekly",taxable:true,notes:""},
{id:crypto.randomUUID(),source:"Weekend job",amount:320,date:todayPlus(-10),frequency:"once",taxable:true,notes:"Side work"}
]);
const[expenses,setExpenses]=useLS<Expense[]>("mmb_expenses",[
{id:crypto.randomUUID(),name:"Fuel for work",amount:80,date:todayPlus(-4),category:"Fuel",taxDeductible:true,gstIncluded:true,notes:""},
{id:crypto.randomUUID(),name:"Tools / bits",amount:145,date:todayPlus(-12),category:"Tools",taxDeductible:true,gstIncluded:true,notes:""}
]);
const[settings,setSettings]=useLS<SettingsType>("mmb_settings",{currency:"AUD",payday:todayPlus(5),safetyBuffer:300,homeAssistantWebhook:"",taxRate:25});
const[tab,setTab]=useState("dashboard");const[modal,setModal]=useState<any>(null);const[editingIncome,setEditingIncome]=useState<Income|null>(null);const[monthOffset,setMonthOffset]=useState(0);

const upcoming=useMemo(()=>bills.filter(b=>!b.paid).sort((a,b)=>new Date(a.dueDate).getTime()-new Date(b.dueDate).getTime()),[bills]);
const mBills=bills.reduce((s,b)=>s+monthlyBill(b.amount,b.frequency),0);
const mIncome=incomes.reduce((s,i)=>s+monthlyIncome(i.amount,i.frequency),0);
const yearlyIncome=incomes.reduce((s,i)=>s+(i.frequency==="weekly"?i.amount*52:i.frequency==="fortnightly"?i.amount*26:i.frequency==="monthly"?i.amount*12:i.amount),0);
const yearlyExpenses=expenses.reduce((s,e)=>s+e.amount,0);
const deductible=expenses.filter(e=>e.taxDeductible).reduce((s,e)=>s+e.amount,0);
const gstCredits=expenses.filter(e=>e.gstIncluded).reduce((s,e)=>s+e.amount/11,0);
const taxEstimate=Math.max(0,yearlyIncome-deductible)*(settings.taxRate/100);
const trend=makeTrend(incomes,expenses,bills);
const catTotals=CATS.map(c=>({cat:c,total:bills.filter(b=>b.category===c).reduce((s,b)=>s+monthlyBill(b.amount,b.frequency),0)})).filter(x=>x.total>0);
const expTotals=EXPENSE_CATS.map(c=>({cat:c,total:expenses.filter(e=>e.category===c).reduce((s,e)=>s+e.amount,0)})).filter(x=>x.total>0);

function markPaid(id:string){setBills(p=>p.map(b=>b.id!==id?b:(b.frequency==="once"?{...b,paid:true}:{...b,dueDate:addFreq(b.dueDate,b.frequency)})))}
function exportCSV(){const rows=[["Date","Type","Name","Category","Amount","Tax Deductible","GST Included","Notes"],...expenses.map(e=>[e.date,"Expense",e.name,e.category,e.amount,e.taxDeductible?"Yes":"No",e.gstIncluded?"Yes":"No",e.notes]),...incomes.map(i=>[i.date,"Income",i.source,"Income",i.amount,i.taxable?"Yes":"No","",""])];download("moneymate-tax.csv",rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")}
function exportData(){download("moneymate-backup.json",JSON.stringify({bills,incomes,expenses,settings},null,2),"application/json")}
function download(name:string,text:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()}

return <main className="app"><div className="wrap">
<header className="top"><div className="brand"><div className="logo"><BarChart3/></div>MoneyMate Dashboard</div><div className="actions"><button className="btn secondary" onClick={()=>window.print()}><Printer size={16}/> Print</button><button className="btn secondary" onClick={()=>setModal("settings")}><Settings size={16}/> Settings</button></div></header>
<nav className="tabs">{[["dashboard","Dashboard",BarChart3],["addBill","Add Bills",Plus],["income","Income",Wallet],["calendar","Calendar",CalendarDays],["tax","Tax",ReceiptText],["tools","Tools & Resources",Calculator]].map(([id,name,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`tab ${tab===id?"active":""}`}><Icon size={16}/>{name}</button>)}</nav>

{tab==="dashboard"&&<>
<section className="hero"><div className="pills"><span className="pill teal"><Sparkles size={13}/> New layout</span><span className="pill green">Charts at top</span><span className="pill orange">Income + bills underneath</span></div><h1>Money overview first.</h1><p>Charts and totals now sit at the top. Income and bills sit underneath. Calendar, Add Bills, Income, Tax and Tools are each on their own page.</p><div className="actions"><button className="btn" onClick={()=>setTab("addBill")}><Plus size={16}/> Add bill</button><button className="btn green" onClick={()=>setTab("income")}><Wallet size={16}/> Manage income</button><button className="btn orange" onClick={()=>setTab("tax")}><ReceiptText size={16}/> Tax page</button></div></section>
<section className="grid five"><Stat label="Income/month" value={money(mIncome,settings.currency)}/><Stat label="Bills/month" value={money(mBills,settings.currency)}/><Stat label="Left/month" value={money(mIncome-mBills,settings.currency)}/><Stat label="Tax estimate" value={money(taxEstimate,settings.currency)}/><Stat label="GST credits" value={money(gstCredits,settings.currency)}/></section>
<section className="grid two" style={{marginTop:16}}><Panel title="Income vs outgoing chart"><LineChart data={trend} currency={settings.currency}/></Panel><Panel title="Bill category chart"><Bars data={catTotals} currency={settings.currency}/></Panel></section>
<section className="grid under"><Panel title="Income underneath"><IncomeList incomes={incomes} setIncomes={setIncomes} currency={settings.currency} edit={setEditingIncome}/></Panel><Panel title="Bills underneath"><BillList bills={upcoming.slice(0,8)} currency={settings.currency} markPaid={markPaid} deleteBill={(id:string)=>setBills(p=>p.filter(b=>b.id!==id))}/></Panel></section>
</>}

{tab==="addBill"&&<Panel title="Add Bills page"><button className="btn" onClick={()=>setModal("bill")}><Plus size={16}/> Add new bill</button><br/><br/><BillList bills={bills} currency={settings.currency} markPaid={markPaid} deleteBill={(id:string)=>setBills(p=>p.filter(b=>b.id!==id))}/></Panel>}
{tab==="income"&&<Panel title="Income page - add, edit and delete"><button className="btn green" onClick={()=>setModal("income")}><Plus size={16}/> Add income</button><br/><br/><IncomeList incomes={incomes} setIncomes={setIncomes} currency={settings.currency} edit={setEditingIncome}/></Panel>}
{tab==="calendar"&&<Panel title="Calendar page"><div className="actions" style={{marginBottom:12}}><button className="btn secondary" onClick={()=>setMonthOffset(v=>v-1)}>Previous</button><button className="btn secondary" onClick={()=>setMonthOffset(0)}>Today</button><button className="btn secondary" onClick={()=>setMonthOffset(v=>v+1)}>Next</button></div><Calendar bills={upcoming} monthOffset={monthOffset} currency={settings.currency}/></Panel>}
{tab==="tax"&&<Panel title="Tax page"><div className="actions" style={{marginBottom:12}}><button className="btn orange" onClick={()=>setModal("expense")}><Plus size={16}/> Add expense</button><button className="btn secondary" onClick={exportCSV}><FileSpreadsheet size={16}/> Export CSV</button></div><section className="grid five"><Stat label="Income/year" value={money(yearlyIncome,settings.currency)}/><Stat label="Expenses" value={money(yearlyExpenses,settings.currency)}/><Stat label="Deductible" value={money(deductible,settings.currency)}/><Stat label="GST credits" value={money(gstCredits,settings.currency)}/><Stat label="Tax estimate" value={money(taxEstimate,settings.currency)}/></section><section className="grid two" style={{marginTop:16}}><Bars data={expTotals} currency={settings.currency}/><ExpenseList expenses={expenses} setExpenses={setExpenses} currency={settings.currency}/></section></Panel>}
{tab==="tools"&&<Tools exportData={exportData} exportCSV={exportCSV} setModal={setModal} currency={settings.currency}/>}
{modal&&<AddModal modal={modal} close={()=>setModal(null)} setBills={setBills} setIncomes={setIncomes} setExpenses={setExpenses} settings={settings} setSettings={setSettings}/>}
{editingIncome&&<IncomeEdit income={editingIncome} close={()=>setEditingIncome(null)} save={(i)=>{setIncomes(p=>p.map(x=>x.id===i.id?i:x));setEditingIncome(null)}}/>}
</div></main>
}

function makeTrend(incomes:Income[],expenses:Expense[],bills:Bill[]){const arr=[];const now=new Date();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);const key=d.toISOString().slice(0,7);arr.push({label:d.toLocaleString("en-AU",{month:"short"}),income:incomes.filter(x=>monthKey(x.date)===key).reduce((s,x)=>s+x.amount,0),out:expenses.filter(x=>monthKey(x.date)===key).reduce((s,x)=>s+x.amount,0)+bills.filter(x=>monthKey(x.dueDate)===key).reduce((s,x)=>s+x.amount,0)})}return arr}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><div className="label">{label}</div><div className="value">{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="title"><h2>{title}</h2></div>{children}</section>}
function LineChart({data,currency}:{data:any[];currency:string}){const max=Math.max(...data.flatMap(d=>[d.income,d.out]),1);const pts=(k:string)=>data.map((d,i)=>`${40+i*(300/(data.length-1))},${210-(d[k]/max)*170}`).join(" ");return <div className="chart"><svg className="svg" viewBox="0 0 380 240"><line className="axis" x1="35" y1="215" x2="360" y2="215"/><line className="axis" x1="35" y1="25" x2="35" y2="215"/><polyline points={pts("income")} className="incomeLine"/><polyline points={pts("out")} className="outLine"/>{data.map((d,i)=><text key={d.label} x={40+i*(300/(data.length-1))} y="235" fontSize="11" textAnchor="middle" fill="#667085">{d.label}</text>)}</svg><div className="pills"><span className="pill teal">Income</span><span className="pill orange">Outgoings</span><span className="muted">Max {money(max,currency)}</span></div></div>}
function Bars({data,currency}:{data:any[];currency:string}){const max=Math.max(...data.map(d=>d.total),1);return <div className="chart"><div className="list">{(data.length?data:[{cat:"No data yet",total:0}]).slice(0,9).map(d=><div className="barRow" key={d.cat}><span>{d.cat}</span><div className="bar"><div style={{width:`${d.total/max*100}%`}}/></div><span>{money(d.total,currency)}</span></div>)}</div></div>}
function BillList({bills,currency,markPaid,deleteBill}:any){return <div className="list">{bills.map((b:Bill)=>{const d=daysUntil(b.dueDate);return <div className="item" key={b.id}><div className="itemTop"><div><div className="name">{b.name}</div><span className="muted">{b.category} · {b.frequency}</span></div><b>{money(b.amount,currency)}</b></div><div className="pills"><span className={`pill ${d<8?"red":"orange"}`}>{d<0?`${Math.abs(d)} overdue`:`Due in ${d} days`}</span><span className="pill">{b.dueDate}</span></div><div className="small"><button className="iconBtn" onClick={()=>markPaid(b.id)}><CheckCircle2 size={14}/> Paid / roll</button><button className="iconBtn" onClick={()=>deleteBill(b.id)}><Trash2 size={14}/> Delete</button></div></div>})}</div>}
function IncomeList({incomes,setIncomes,currency,edit}:any){return <div className="list">{incomes.map((i:Income)=><div className="item" key={i.id}><div className="itemTop"><div><div className="name">{i.source}</div><span className="muted">{i.date} · {i.frequency} · {i.taxable?"taxable":"not taxable"}</span></div><b>{money(i.amount,currency)}</b></div>{i.notes&&<span className="muted">{i.notes}</span>}<div className="small"><button className="iconBtn" onClick={()=>edit(i)}><Edit3 size={14}/> Edit</button><button className="iconBtn" onClick={()=>setIncomes((p:Income[])=>p.filter(x=>x.id!==i.id))}><Trash2 size={14}/> Delete</button></div></div>)}</div>}
function ExpenseList({expenses,setExpenses,currency}:any){return <div className="list">{expenses.map((e:Expense)=><div className="item" key={e.id}><div className="itemTop"><div><div className="name">{e.name}</div><span className="muted">{e.date} · {e.category}</span></div><b>{money(e.amount,currency)}</b></div><div className="pills">{e.taxDeductible&&<span className="pill green">Deductible</span>}{e.gstIncluded&&<span className="pill teal">GST {money(e.amount/11,currency)}</span>}</div><button className="iconBtn" onClick={()=>setExpenses((p:Expense[])=>p.filter(x=>x.id!==e.id))}><Trash2 size={14}/> Delete</button></div>)}</div>}
function Calendar({bills,monthOffset,currency}:any){const base=new Date();base.setMonth(base.getMonth()+monthOffset);const y=base.getFullYear(),m=base.getMonth();const start=new Date(y,m,1),end=new Date(y,m+1,0);const blanks=(start.getDay()+6)%7;const days=Array.from({length:blanks+end.getDate()},(_,i)=>i<blanks?null:i-blanks+1);return <><h2>{base.toLocaleString("en-AU",{month:"long",year:"numeric"})}</h2><div className="calendar">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div className="dayHead" key={d}>{d}</div>)}{days.map((day,i)=>{if(!day)return <div key={i}/>;const iso=new Date(y,m,day+1).toISOString().slice(0,10);const bs=bills.filter((b:Bill)=>b.dueDate===iso);return <div className={`day ${iso===todayISO()?"today":""}`} key={i}><b>{day}</b>{bs.map((b:Bill)=><div className="calBill" key={b.id}>{b.name} {money(b.amount,currency)}</div>)}</div>})}</div></>}
function Tools({exportData,exportCSV,setModal,currency}:any){return <section className="grid two"><Panel title="Calculators"><Calculators currency={currency}/></Panel><Panel title="Resources"><div className="grid three"><Tool title="Backup" text="Download all app data." action={exportData}/><Tool title="Tax CSV" text="Export tax records." action={exportCSV}/><Tool title="Settings" text="Home Assistant and app settings." action={()=>setModal("settings")}/></div></Panel></section>}
function Tool({title,text,action}:any){return <div className="item"><b>{title}</b><span className="muted">{text}</span><button className="btn secondary" onClick={action}>Open</button></div>}
function Calculators({currency}:any){const[loan,setLoan]=useState({amount:5000,rate:12,months:36});const[gst,setGst]=useState(110);const pay=(loan.amount*(loan.rate/100/12))/(1-Math.pow(1+loan.rate/100/12,-loan.months));return <div className="list"><div className="item"><b>Loan repayment</b><div className="form"><input type="number" value={loan.amount} onChange={e=>setLoan({...loan,amount:Number(e.target.value)})}/><input type="number" value={loan.rate} onChange={e=>setLoan({...loan,rate:Number(e.target.value)})}/><input type="number" value={loan.months} onChange={e=>setLoan({...loan,months:Number(e.target.value)})}/></div><div className="value">{money(pay||0,currency)}/month</div></div><div className="item"><b>GST calculator</b><input type="number" value={gst} onChange={e=>setGst(Number(e.target.value))}/><span>GST: <b>{money(gst/11,currency)}</b> · Ex GST: <b>{money(gst-gst/11,currency)}</b></span></div></div>}
function ModalShell({title,children,close}:any){return <div className="modalWrap"><div className="modal"><div className="title"><h2>{title}</h2><button className="iconBtn" onClick={close}><X size={14}/> Close</button></div>{children}</div></div>}
function Field({label,children,full}:any){return <div className={`field ${full?"full":""}`}><label>{label}</label>{children}</div>}
function IncomeEdit({income,save,close}:any){const[f,setF]=useState(income);return <ModalShell title="Edit income" close={close}><div className="form"><Field label="Source"><input value={f.source} onChange={e=>setF({...f,source:e.target.value})}/></Field><Field label="Amount"><input type="number" value={f.amount} onChange={e=>setF({...f,amount:Number(e.target.value)})}/></Field><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Frequency"><select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{["once","weekly","fortnightly","monthly"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Taxable"><select value={String(f.taxable)} onChange={e=>setF({...f,taxable:e.target.value==="true"})}><option value="true">Yes</option><option value="false">No</option></select></Field><Field label="Notes" full><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></div><br/><button className="btn green" onClick={()=>save(f)}><Save size={16}/> Save income</button></ModalShell>}
function AddModal({modal,close,setBills,setIncomes,setExpenses,settings,setSettings}:any){const[f,setF]=useState<any>({name:"",source:"",amount:"",date:todayISO(),dueDate:todayISO(),category:"Home",frequency:"monthly",autopay:false,notes:"",taxDeductible:true,gstIncluded:true,currency:settings.currency,payday:settings.payday,safetyBuffer:settings.safetyBuffer,homeAssistantWebhook:settings.homeAssistantWebhook,taxRate:settings.taxRate});
if(modal==="settings")return <ModalShell title="Settings" close={close}><div className="form"><Field label="Currency"><input value={f.currency} onChange={e=>setF({...f,currency:e.target.value.toUpperCase()})}/></Field><Field label="Payday"><input type="date" value={f.payday} onChange={e=>setF({...f,payday:e.target.value})}/></Field><Field label="Safety buffer"><input type="number" value={f.safetyBuffer} onChange={e=>setF({...f,safetyBuffer:Number(e.target.value)})}/></Field><Field label="Tax rate %"><input type="number" value={f.taxRate} onChange={e=>setF({...f,taxRate:Number(e.target.value)})}/></Field><Field label="Home Assistant webhook" full><input value={f.homeAssistantWebhook} onChange={e=>setF({...f,homeAssistantWebhook:e.target.value})}/></Field></div><br/><button className="btn" onClick={()=>{setSettings({currency:f.currency,payday:f.payday,safetyBuffer:Number(f.safetyBuffer),homeAssistantWebhook:f.homeAssistantWebhook,taxRate:Number(f.taxRate)});close()}}>Save settings</button></ModalShell>;
return <ModalShell title={`Add ${modal}`} close={close}><div className="form">{modal==="income"?<Field label="Source"><input value={f.source} onChange={e=>setF({...f,source:e.target.value})}/></Field>:<Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field>}<Field label="Amount"><input type="number" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field>{modal==="bill"&&<><Field label="Due date"><input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></Field><Field label="Category"><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Frequency"><select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{["once","weekly","fortnightly","monthly","quarterly","yearly"].map(x=><option key={x}>{x}</option>)}</select></Field></>}{modal==="income"&&<><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Frequency"><select value={f.frequency} onChange={e=>setF({...f,frequency:e.target.value})}>{["once","weekly","fortnightly","monthly"].map(x=><option key={x}>{x}</option>)}</select></Field></>}{modal==="expense"&&<><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Category"><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{EXPENSE_CATS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Tax deductible"><select value={String(f.taxDeductible)} onChange={e=>setF({...f,taxDeductible:e.target.value==="true"})}><option value="true">Yes</option><option value="false">No</option></select></Field><Field label="GST included"><select value={String(f.gstIncluded)} onChange={e=>setF({...f,gstIncluded:e.target.value==="true"})}><option value="true">Yes</option><option value="false">No</option></select></Field></>}<Field label="Notes" full><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field></div><br/><button className="btn" onClick={()=>{if(modal==="bill")setBills((x:Bill[])=>[{id:crypto.randomUUID(),name:f.name,amount:Number(f.amount),dueDate:f.dueDate,category:f.category,frequency:f.frequency,paid:false,autopay:f.autopay,notes:f.notes},...x]);if(modal==="income")setIncomes((x:Income[])=>[{id:crypto.randomUUID(),source:f.source,amount:Number(f.amount),date:f.date,frequency:f.frequency,taxable:true,notes:f.notes},...x]);if(modal==="expense")setExpenses((x:Expense[])=>[{id:crypto.randomUUID(),name:f.name,amount:Number(f.amount),date:f.date,category:f.category,taxDeductible:f.taxDeductible,gstIncluded:f.gstIncluded,notes:f.notes},...x]);close()}}>Save</button></ModalShell>}
