import React, { useMemo, useState, useEffect } from 'react';
import { BarChart3, CalendarDays, Download, FileSpreadsheet, Plus, Save, Settings, Trash2, Upload, Wallet, Bell, Banknote, Calculator, ReceiptText, AlertTriangle } from 'lucide-react';

const CATEGORIES = ['Income','Rent/Mortgage','Utilities','Phone/Internet','Fuel','Groceries','Kids','Insurance','Debt','Subscriptions','Business','Tools','Health','Fun','Savings','Tax','Other'];
const todayISO = () => new Date().toISOString().slice(0,10);
const addDays = (n) => { const d = new Date(); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
const uid = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2);
function money(n,c='AUD'){ return new Intl.NumberFormat('en-AU',{style:'currency',currency:c}).format(Number.isFinite(Number(n))?Number(n):0); }
function daysUntil(date){ return Math.round((new Date(date).getTime()-new Date(todayISO()).getTime())/86400000); }
function monthKey(date){ return String(date||'').slice(0,7); }
function useLocalStorage(key,fallback){ const [v,setV]=useState(fallback); useEffect(()=>{try{const s=localStorage.getItem(key); if(s) setV(JSON.parse(s));}catch{}},[key]); useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(v));}catch{}},[key,v]); return [v,setV]; }

const starterTransactions=[
{id:uid(),date:addDays(-10),type:'income',description:'Main pay',category:'Income',amount:1250,account:'Everyday',billName:'',taxDeductible:false,gstIncluded:false,notes:'Weekly pay'},
{id:uid(),date:addDays(-8),type:'expense',description:'Groceries',category:'Groceries',amount:210,account:'Everyday',billName:'',taxDeductible:false,gstIncluded:false,notes:''},
{id:uid(),date:addDays(-4),type:'expense',description:'Fuel',category:'Fuel',amount:80,account:'Everyday',billName:'',taxDeductible:true,gstIncluded:true,notes:'Work travel'},
{id:uid(),date:addDays(-2),type:'saving',description:'Emergency buffer',category:'Savings',amount:100,account:'Savings',billName:'',taxDeductible:false,gstIncluded:false,notes:''}
];
const starterBills=[
{id:uid(),name:'Rent / Mortgage',amount:450,dueDate:addDays(3),frequency:'weekly',category:'Rent/Mortgage',paid:false,autopay:false,reminderDays:3,notes:'Main housing payment'},
{id:uid(),name:'Electricity',amount:180,dueDate:addDays(11),frequency:'quarterly',category:'Utilities',paid:false,autopay:false,reminderDays:7,notes:''},
{id:uid(),name:'Phone',amount:65,dueDate:addDays(7),frequency:'monthly',category:'Phone/Internet',paid:false,autopay:true,reminderDays:3,notes:''}
];
const starterIncome=[{id:uid(),source:'Main pay',amount:1250,nextDate:addDays(5),frequency:'weekly',taxable:true,notes:''}];

export default function App(){
 const [tab,setTab]=useState('dashboard');
 const [transactions,setTransactions]=useLocalStorage('moneytalks_transactions',starterTransactions);
 const [bills,setBills]=useLocalStorage('moneytalks_bills',starterBills);
 const [income,setIncome]=useLocalStorage('moneytalks_income',starterIncome);
 const [settings,setSettings]=useLocalStorage('moneytalks_settings',{currency:'AUD',taxRate:25,savingsGoal:2000,safetyBuffer:500});
 const [monthOffset,setMonthOffset]=useState(0);
 const summary=useMemo(()=>buildSummary(transactions,settings),[transactions,settings]);
 function exportBackup(){downloadFile('moneytalks-backup.json',JSON.stringify({transactions,bills,income,settings},null,2),'application/json');}
 function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result)); if(Array.isArray(d.transactions))setTransactions(d.transactions); if(Array.isArray(d.bills))setBills(d.bills); if(Array.isArray(d.income))setIncome(d.income); if(d.settings)setSettings(d.settings);}catch{alert('Backup import failed.')}}; r.readAsText(file);}
 function exportCsv(){const rows=[['date','type','description','category','amount','account','billName','taxDeductible','gstIncluded','notes'],...transactions.map(t=>[t.date,t.type,t.description,t.category,t.amount,t.account,t.billName,t.taxDeductible,t.gstIncluded,t.notes])]; downloadFile('moneytalks-transactions.csv',toCsv(rows),'text/csv');}
 function importCsv(file){const r=new FileReader(); r.onload=()=>{const rows=parseCsv(String(r.result||'')); if(!rows.length)return alert('No rows found.'); const [headers,...body]=rows; const hs=headers.map(h=>h.trim().toLowerCase().replaceAll(' ','')); const imported=body.filter(row=>row.some(Boolean)).map(row=>{const o={}; hs.forEach((h,i)=>o[h]=row[i]||''); const amount=Number(String(o.amount||o.debit||o.credit||'0').replace(/[^0-9.-]/g,'')); const desc=o.description||o.details||o.transaction||o.narration||'Imported transaction'; const isIncome=Number(o.credit||0)>0||String(o.type).toLowerCase()==='income'; return {id:uid(),date:o.date||o.transactiondate||todayISO(),type:o.type||(isIncome?'income':'expense'),description:desc,category:o.category||autoCategory(desc),amount:Math.abs(amount),account:o.account||'Imported',billName:o.billname||'',taxDeductible:String(o.taxdeductible).toLowerCase()==='true',gstIncluded:String(o.gstincluded).toLowerCase()==='true',notes:o.notes||'Imported CSV'};}); setTransactions(prev=>[...imported,...prev]); alert(`Imported ${imported.length} rows.`);}; r.readAsText(file);}
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="logo"><FileSpreadsheet/></div><span>MoneyTalks Ledger</span></div><div className="actions"><button className="btn secondary" onClick={exportBackup}><Download size={16}/> Backup</button><label className="btn secondary"><Upload size={16}/> Restore<input hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importBackup(e.target.files[0])}/></label></div></header><nav className="nav">{[['dashboard','Dashboard',BarChart3],['transactions','Spreadsheet',FileSpreadsheet],['bills','Bills',Bell],['income','Income',Wallet],['calendar','Calendar',CalendarDays],['tax','Tax',ReceiptText],['bank','Bank Sync',Banknote],['tools','Tools',Calculator]].map(([id,name,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{name}</button>)}</nav>{tab==='dashboard'&&<Dashboard summary={summary} transactions={transactions} bills={bills} income={income} settings={settings} setTab={setTab}/>} {tab==='transactions'&&<TransactionsPage transactions={transactions} setTransactions={setTransactions} settings={settings} exportCsv={exportCsv} importCsv={importCsv}/>} {tab==='bills'&&<BillsPage bills={bills} setBills={setBills} settings={settings} setTransactions={setTransactions}/>} {tab==='income'&&<IncomePage income={income} setIncome={setIncome} settings={settings} setTransactions={setTransactions}/>} {tab==='calendar'&&<CalendarPage bills={bills} income={income} settings={settings} monthOffset={monthOffset} setMonthOffset={setMonthOffset}/>} {tab==='tax'&&<TaxPage transactions={transactions} settings={settings} setSettings={setSettings} exportCsv={exportCsv}/>} {tab==='bank'&&<BankSyncPage importCsv={importCsv}/>} {tab==='tools'&&<ToolsPage settings={settings} setSettings={setSettings} summary={summary}/>}</main>;
}

function Dashboard({summary,transactions,bills,income,settings,setTab}){const trend=buildTrend(transactions); const bars=buildCategoryBars(transactions); const reminders=bills.filter(b=>!b.paid).map(b=>({...b,days:daysUntil(b.dueDate)})).filter(b=>b.days<=Number(b.reminderDays||3)||b.days<=7).sort((a,b)=>a.days-b.days); return <><section className="hero"><div className="pills"><span className="pill teal"><FileSpreadsheet size={13}/> Spreadsheet-first</span><span className="pill green">Everything editable</span><span className="pill orange">Bills + income + tax</span></div><h1>Your money, in one readable ledger.</h1><p>Track every in and out, bills, savings, tax, income, reminders and CSV bank imports. Built like a spreadsheet so you can edit anything quickly.</p><div className="actions"><button className="btn" onClick={()=>setTab('transactions')}><FileSpreadsheet size={16}/> Open Spreadsheet</button><button className="btn green" onClick={()=>setTab('bills')}><Bell size={16}/> Bills</button><button className="btn orange" onClick={()=>setTab('bank')}><Banknote size={16}/> Import Bank CSV</button></div></section><section className="grid stats"><Stat label="Incoming" value={money(summary.incoming,settings.currency)}/><Stat label="Outgoing" value={money(summary.outgoing,settings.currency)}/><Stat label="Savings" value={money(summary.savings,settings.currency)}/><Stat label="Net position" value={money(summary.net,settings.currency)}/><Stat label="Tax estimate" value={money(summary.taxEstimate,settings.currency)}/><Stat label="GST credits" value={money(summary.gstCredits,settings.currency)}/></section><section className="grid two" style={{marginTop:16}}><Panel title="Incoming / outgoing / savings graph"><LineChart data={trend} currency={settings.currency}/></Panel><Panel title="Spending by category"><Bars data={bars} currency={settings.currency}/></Panel></section><section className="grid dashboard-main" style={{marginTop:16}}><Panel title="Bill reminders"><div className="reminder-list">{reminders.length===0&&<div className="reminder-item">No urgent bills right now.</div>}{reminders.map(b=><div className="reminder-item" key={b.id}><strong>{b.name}</strong><div>{money(b.amount,settings.currency)} due {b.dueDate}</div><div className="muted">{b.days<0?`${Math.abs(b.days)} days overdue`:`${b.days} days away`}</div></div>)}</div></Panel><Panel title="Quick income view"><div className="sheet-wrap"><table className="sheet-table"><thead><tr><th>Source</th><th>Amount</th><th>Next Date</th><th>Frequency</th></tr></thead><tbody>{income.map(i=><tr key={i.id}><td>{i.source}</td><td>{money(i.amount,settings.currency)}</td><td>{i.nextDate}</td><td>{i.frequency}</td></tr>)}</tbody></table></div></Panel></section></>}
function TransactionsPage({transactions,setTransactions,exportCsv,importCsv}){function add(){setTransactions(p=>[{id:uid(),date:todayISO(),type:'expense',description:'',category:'Other',amount:0,account:'',billName:'',taxDeductible:false,gstIncluded:false,notes:''},...p])} function upd(id,f,v){setTransactions(p=>p.map(r=>r.id===id?{...r,[f]:v}:r))} return <Panel title="Spreadsheet Ledger"><div className="actions" style={{marginBottom:12}}><button className="btn" onClick={add}><Plus size={16}/> Add row</button><button className="btn secondary" onClick={exportCsv}><Download size={16}/> Export CSV</button><label className="btn secondary"><Upload size={16}/> Import CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/></label></div><div className="sheet-wrap"><table className="sheet-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Category</th><th>Amount</th><th>Account</th><th>Linked Bill</th><th>Tax Deductible</th><th>GST</th><th>Notes</th><th></th></tr></thead><tbody>{transactions.map(row=><tr key={row.id}><td><input type="date" value={row.date} onChange={e=>upd(row.id,'date',e.target.value)}/></td><td><select value={row.type} onChange={e=>upd(row.id,'type',e.target.value)}><option>income</option><option>expense</option><option>saving</option><option>tax</option></select></td><td><input value={row.description} onChange={e=>upd(row.id,'description',e.target.value)}/></td><td><select value={row.category} onChange={e=>upd(row.id,'category',e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></td><td><input type="number" value={row.amount} onChange={e=>upd(row.id,'amount',Number(e.target.value))}/></td><td><input value={row.account} onChange={e=>upd(row.id,'account',e.target.value)}/></td><td><input value={row.billName} onChange={e=>upd(row.id,'billName',e.target.value)}/></td><td><input type="checkbox" checked={!!row.taxDeductible} onChange={e=>upd(row.id,'taxDeductible',e.target.checked)}/></td><td><input type="checkbox" checked={!!row.gstIncluded} onChange={e=>upd(row.id,'gstIncluded',e.target.checked)}/></td><td><input value={row.notes} onChange={e=>upd(row.id,'notes',e.target.value)}/></td><td><button className="icon-btn" onClick={()=>setTransactions(p=>p.filter(x=>x.id!==row.id))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></Panel>}
function BillsPage({bills,setBills,settings,setTransactions}){function add(){setBills(p=>[{id:uid(),name:'',amount:0,dueDate:todayISO(),frequency:'monthly',category:'Other',paid:false,autopay:false,reminderDays:3,notes:''},...p])} function upd(id,f,v){setBills(p=>p.map(b=>b.id===id?{...b,[f]:v}:b))} function markPaid(b){setTransactions(p=>[{id:uid(),date:todayISO(),type:'expense',description:b.name,category:b.category,amount:Number(b.amount),account:'',billName:b.name,taxDeductible:false,gstIncluded:false,notes:'Marked paid from bills'},...p]); upd(b.id,'paid',true)} return <Panel title="Bills Spreadsheet"><div className="actions" style={{marginBottom:12}}><button className="btn" onClick={add}><Plus size={16}/> Add bill</button></div><div className="sheet-wrap"><table className="sheet-table"><thead><tr><th>Name</th><th>Amount</th><th>Due Date</th><th>Frequency</th><th>Category</th><th>Reminder Days</th><th>Autopay</th><th>Paid</th><th>Notes</th><th></th></tr></thead><tbody>{bills.map(b=><tr key={b.id}><td><input value={b.name} onChange={e=>upd(b.id,'name',e.target.value)}/></td><td><input type="number" value={b.amount} onChange={e=>upd(b.id,'amount',Number(e.target.value))}/></td><td><input type="date" value={b.dueDate} onChange={e=>upd(b.id,'dueDate',e.target.value)}/></td><td><select value={b.frequency} onChange={e=>upd(b.id,'frequency',e.target.value)}>{['once','weekly','fortnightly','monthly','quarterly','yearly'].map(x=><option key={x}>{x}</option>)}</select></td><td><select value={b.category} onChange={e=>upd(b.id,'category',e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></td><td><input type="number" value={b.reminderDays} onChange={e=>upd(b.id,'reminderDays',Number(e.target.value))}/></td><td><input type="checkbox" checked={!!b.autopay} onChange={e=>upd(b.id,'autopay',e.target.checked)}/></td><td><input type="checkbox" checked={!!b.paid} onChange={e=>upd(b.id,'paid',e.target.checked)}/></td><td><input value={b.notes} onChange={e=>upd(b.id,'notes',e.target.value)}/></td><td className="actions"><button className="icon-btn" onClick={()=>markPaid(b)}><Save size={14}/></button><button className="icon-btn" onClick={()=>setBills(p=>p.filter(x=>x.id!==b.id))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></Panel>}
function IncomePage({income,setIncome,settings,setTransactions}){function add(){setIncome(p=>[{id:uid(),source:'',amount:0,nextDate:todayISO(),frequency:'weekly',taxable:true,notes:''},...p])} function upd(id,f,v){setIncome(p=>p.map(i=>i.id===id?{...i,[f]:v}:i))} function log(i){setTransactions(p=>[{id:uid(),date:todayISO(),type:'income',description:i.source,category:'Income',amount:Number(i.amount),account:'',billName:'',taxDeductible:false,gstIncluded:false,notes:'Logged from income'},...p])} return <Panel title="Income Spreadsheet"><div className="actions" style={{marginBottom:12}}><button className="btn green" onClick={add}><Plus size={16}/> Add income</button></div><div className="sheet-wrap"><table className="sheet-table"><thead><tr><th>Source</th><th>Amount</th><th>Next Date</th><th>Frequency</th><th>Taxable</th><th>Notes</th><th></th></tr></thead><tbody>{income.map(i=><tr key={i.id}><td><input value={i.source} onChange={e=>upd(i.id,'source',e.target.value)}/></td><td><input type="number" value={i.amount} onChange={e=>upd(i.id,'amount',Number(e.target.value))}/></td><td><input type="date" value={i.nextDate} onChange={e=>upd(i.id,'nextDate',e.target.value)}/></td><td><select value={i.frequency} onChange={e=>upd(i.id,'frequency',e.target.value)}>{['once','weekly','fortnightly','monthly'].map(x=><option key={x}>{x}</option>)}</select></td><td><input type="checkbox" checked={!!i.taxable} onChange={e=>upd(i.id,'taxable',e.target.checked)}/></td><td><input value={i.notes} onChange={e=>upd(i.id,'notes',e.target.value)}/></td><td className="actions"><button className="icon-btn" onClick={()=>log(i)}><Save size={14}/></button><button className="icon-btn" onClick={()=>setIncome(p=>p.filter(x=>x.id!==i.id))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></Panel>}
function CalendarPage({bills,income,settings,monthOffset,setMonthOffset}){const base=new Date(); base.setMonth(base.getMonth()+monthOffset); const y=base.getFullYear(),m=base.getMonth(); const start=new Date(y,m,1),end=new Date(y,m+1,0); const blanks=(start.getDay()+6)%7; const days=Array.from({length:blanks+end.getDate()},(_,i)=>i<blanks?null:i-blanks+1); return <Panel title="Calendar"><div className="actions" style={{marginBottom:12}}><button className="btn secondary" onClick={()=>setMonthOffset(v=>v-1)}>Previous</button><button className="btn secondary" onClick={()=>setMonthOffset(0)}>Today</button><button className="btn secondary" onClick={()=>setMonthOffset(v=>v+1)}>Next</button></div><h2>{base.toLocaleString('en-AU',{month:'long',year:'numeric'})}</h2><div className="calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><div className="day-head" key={d}>{d}</div>)}{days.map((day,i)=>{if(!day)return <div key={i}/>; const iso=new Date(y,m,day+1).toISOString().slice(0,10); const bs=bills.filter(b=>b.dueDate===iso); const incs=income.filter(inc=>inc.nextDate===iso); return <div className={`day ${iso===todayISO()?'today':''}`} key={i}><strong>{day}</strong>{bs.map(b=><div className="cal-item cal-bill" key={b.id}>{b.name} {money(b.amount,settings.currency)}</div>)}{incs.map(inc=><div className="cal-item cal-income" key={inc.id}>{inc.source} {money(inc.amount,settings.currency)}</div>)}</div>})}</div></Panel>}
function TaxPage({transactions,settings,setSettings,exportCsv}){const incomeTotal=transactions.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0); const deductible=transactions.filter(t=>t.taxDeductible).reduce((s,t)=>s+Number(t.amount||0),0); const gstCredits=transactions.filter(t=>t.gstIncluded).reduce((s,t)=>s+Number(t.amount||0)/11,0); const taxable=Math.max(0,incomeTotal-deductible); const taxEstimate=taxable*(Number(settings.taxRate||0)/100); return <><section className="grid stats"><Stat label="Income tracked" value={money(incomeTotal,settings.currency)}/><Stat label="Deductions" value={money(deductible,settings.currency)}/><Stat label="Taxable estimate" value={money(taxable,settings.currency)}/><Stat label="Tax estimate" value={money(taxEstimate,settings.currency)}/><Stat label="GST credits" value={money(gstCredits,settings.currency)}/><Stat label="Tax rate" value={`${settings.taxRate}%`}/></section><Panel title="Tax System"><div className="warning"><AlertTriangle size={16}/> This is a tracker and estimate only, not tax advice. Keep receipts and check with an accountant.</div><br/><div className="form-grid"><div className="field"><label>Tax rate estimate %</label><input type="number" value={settings.taxRate} onChange={e=>setSettings({...settings,taxRate:Number(e.target.value)})}/></div><div className="field"><label>Currency</label><input value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value.toUpperCase()})}/></div></div><br/><button className="btn secondary" onClick={exportCsv}><Download size={16}/> Export transactions for accountant</button></Panel></>}
function BankSyncPage({importCsv}){return <Panel title="Commonwealth / Bank Sync"><div className="bank-card"><h3>Safe version now: CSV import</h3><p className="muted">Export transactions from your bank, then import the CSV here. The app will try to map date, description and amount columns.</p><label className="btn orange"><Upload size={16}/> Import bank CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/></label></div><br/><div className="bank-card"><h3>Real automatic CommBank sync</h3><p>Automatic Commonwealth Bank syncing should use Open Banking through Australia's Consumer Data Right with an accredited provider. Do not use NetBank password scraping or store bank passwords.</p><p className="muted">Future build path: add a backend, connect to a CDR/Open Banking provider, store tokens server-side, then sync accounts and transactions into this ledger.</p></div></Panel>}
function ToolsPage({settings,setSettings,summary}){const [loan,setLoan]=useState({amount:5000,rate:12,months:36}); const [target,setTarget]=useState({goal:settings.savingsGoal,current:summary.savings,months:12}); const mr=Number(loan.rate)/100/12; const loanPay=mr?(loan.amount*mr)/(1-Math.pow(1+mr,-loan.months)):loan.amount/loan.months; return <section className="grid two"><Panel title="Calculators"><div className="grid two"><div className="bank-card"><h3>Loan repayment</h3><div className="form-grid"><input type="number" value={loan.amount} onChange={e=>setLoan({...loan,amount:Number(e.target.value)})}/><input type="number" value={loan.rate} onChange={e=>setLoan({...loan,rate:Number(e.target.value)})}/><input type="number" value={loan.months} onChange={e=>setLoan({...loan,months:Number(e.target.value)})}/></div><h2>{money(loanPay||0,settings.currency)} / month</h2></div><div className="bank-card"><h3>Savings target</h3><div className="form-grid"><input type="number" value={target.goal} onChange={e=>setTarget({...target,goal:Number(e.target.value)})}/><input type="number" value={target.current} onChange={e=>setTarget({...target,current:Number(e.target.value)})}/><input type="number" value={target.months} onChange={e=>setTarget({...target,months:Number(e.target.value)})}/></div><h2>{money((target.goal-target.current)/Math.max(1,target.months),settings.currency)} / month</h2></div></div></Panel><Panel title="App Settings"><div className="form-grid"><div className="field"><label>Currency</label><input value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value.toUpperCase()})}/></div><div className="field"><label>Savings goal</label><input type="number" value={settings.savingsGoal} onChange={e=>setSettings({...settings,savingsGoal:Number(e.target.value)})}/></div><div className="field"><label>Safety buffer</label><input type="number" value={settings.safetyBuffer} onChange={e=>setSettings({...settings,safetyBuffer:Number(e.target.value)})}/></div></div></Panel></section>}
function Panel({title,children}){return <section className="panel"><div className="panel-title"><h2>{title}</h2></div>{children}</section>}
function Stat({label,value}){return <div className="stat"><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>}
function LineChart({data,currency}){const max=Math.max(...data.flatMap(d=>[d.income,d.outgoing,d.saving]),1); const pts=k=>data.map((d,i)=>`${40+i*(300/Math.max(1,data.length-1))},${210-(d[k]/max)*170}`).join(' '); return <div className="chart-box"><svg className="svg-chart" viewBox="0 0 380 245"><line className="axis" x1="35" y1="215" x2="360" y2="215"/><line className="axis" x1="35" y1="25" x2="35" y2="215"/><polyline points={pts('income')} className="income-line"/><polyline points={pts('outgoing')} className="out-line"/><polyline points={pts('saving')} className="saving-line"/>{data.map((d,i)=><text key={d.label} x={40+i*(300/Math.max(1,data.length-1))} y="238" fontSize="11" textAnchor="middle" fill="#667085">{d.label}</text>)}</svg><div className="pills"><span className="pill teal">Incoming</span><span className="pill orange">Outgoing</span><span className="pill">Savings</span><span className="muted">Max {money(max,currency)}</span></div></div>}
function Bars({data,currency}){const max=Math.max(...data.map(d=>d.total),1); return <div className="chart-box"><div className="bar-list">{(data.length?data:[{category:'No data yet',total:0}]).slice(0,10).map(d=><div className="bar-row" key={d.category}><span>{d.category}</span><div className="bar"><div style={{width:`${(d.total/max)*100}%`}}/></div><span>{money(d.total,currency)}</span></div>)}</div></div>}
function buildSummary(transactions,settings){const incoming=transactions.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0); const outgoing=transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0); const savings=transactions.filter(t=>t.type==='saving'||t.category==='Savings').reduce((s,t)=>s+Number(t.amount||0),0); const taxPaid=transactions.filter(t=>t.type==='tax'||t.category==='Tax').reduce((s,t)=>s+Number(t.amount||0),0); const deductible=transactions.filter(t=>t.taxDeductible).reduce((s,t)=>s+Number(t.amount||0),0); const gstCredits=transactions.filter(t=>t.gstIncluded).reduce((s,t)=>s+Number(t.amount||0)/11,0); const taxEstimate=Math.max(0,incoming-deductible)*(Number(settings.taxRate||0)/100); return {incoming,outgoing,savings,taxPaid,deductible,gstCredits,taxEstimate,net:incoming-outgoing-savings-taxPaid}}
function buildTrend(transactions){const now=new Date(); const months=[]; for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1); const key=d.toISOString().slice(0,7); const rows=transactions.filter(t=>monthKey(t.date)===key); months.push({label:d.toLocaleString('en-AU',{month:'short'}),income:rows.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount||0),0),outgoing:rows.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0),saving:rows.filter(t=>t.type==='saving'||t.category==='Savings').reduce((s,t)=>s+Number(t.amount||0),0)});} return months;}
function buildCategoryBars(transactions){return CATEGORIES.map(category=>({category,total:transactions.filter(t=>t.type==='expense'&&t.category===category).reduce((s,t)=>s+Number(t.amount||0),0)})).filter(x=>x.total>0).sort((a,b)=>b.total-a.total)}
function downloadFile(name,text,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click();}
function toCsv(rows){return rows.map(r=>r.map(cell=>`"${String(cell??'').replaceAll('"','""')}"`).join(',')).join('\n')}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++;}else if(ch==='"'){q=!q;}else if(ch===','&&!q){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!q){if(cell||row.length){row.push(cell);rows.push(row);row=[];cell='';} if(ch==='\r'&&nx==='\n')i++;}else cell+=ch;} if(cell||row.length){row.push(cell);rows.push(row);} return rows;}
function autoCategory(text){const t=String(text||'').toLowerCase(); if(t.includes('woolworths')||t.includes('coles')||t.includes('aldi'))return 'Groceries'; if(t.includes('fuel')||t.includes('shell')||t.includes('bp')||t.includes('otr'))return 'Fuel'; if(t.includes('rent'))return 'Rent/Mortgage'; if(t.includes('telstra')||t.includes('optus')||t.includes('vodafone'))return 'Phone/Internet'; if(t.includes('insurance'))return 'Insurance'; if(t.includes('netflix')||t.includes('spotify')||t.includes('subscription'))return 'Subscriptions'; return 'Other';}
